#!/usr/bin/env bash
# Configures a new Ubuntu machine to have Nginx with a custom HTTP response header X-Served-By
apt-get update -y
apt-get install -y nginx
ufw allow 'Nginx HTTP' 2>/dev/null || true
HOSTNAME=$(hostname)
NGINX_CONF="/etc/nginx/sites-available/default"
if ! grep -q "X-Served-By" "$NGINX_CONF"; then
	sed -i "/server_name _;/a \\\tadd_header X-Served-By $HOSTNAME;" "$NGINX_CONF"
fi
nginx -t && systemctl restart nginx
