#!/usr/bin/env bash
# Configures a new Ubuntu machine to have Nginx with a custom HTTP response header X-Served-By
apt-get update -y
apt-get install -y nginx
ufw allow 'Nginx HTTP' 2>/dev/null || true
HOSTNAME=$(hostname)
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	add_header X-Served-By $HOSTNAME;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
}" > /etc/nginx/sites-available/default
nginx -t && systemctl restart nginx
