#!/usr/bin/env bash
# Configures a new Ubuntu machine to install and configure HAproxy as a load balancer

apt-get update -y
apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

cat >> /etc/haproxy/haproxy.cfg << 'EOF'

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 18.234.221.151:80 check
    server web-02 52.87.243.104:80 check
EOF

service haproxy restart
