#!/usr/bin/env bash
# Configures a new Ubuntu machine to install and configure HAproxy as a load balancer

apt-get update -y
apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

cat > /etc/haproxy/haproxy.cfg << EOF
global
	log /dev/log local0
	log /dev/log local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

defaults
	log global
	mode http
	option httplog
	option dontlognull
	timeout connect 5000
	timeout client  50000
	timeout server  50000

frontend http_front
	bind *:80
	default_backend http_back

backend http_back
	balance roundrobin
	server 7027-web-01 18.234.221.151:80 check
	server 7027-web-02 52.87.243.104:80 check
EOF

service haproxy restart
