#!/usr/bin/env bash
# 0-transfer_file.sh
#script that transfers file from local machine to a remote server using scp command

# Check if fewer than 4 arguments were passed
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to readable variables
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

# Transfer the file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/