#!/usr/bin/env bash
# 0-transfer_file.sh
#script that transfers file from local machine to a remote server using scp command

if ["$#" -eq  3 || "$#" -eq 4]; then
    echo "User entered 3 or 4 arguments"
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    if ["$#" -lt 4]; then
        scp "$1" "$3"@"$2":~/
        exit 1
    else
        FILE_PATH="$1"
        SERVER_IP="$2"
        USERNAME="$3"
        SSH_KEY_PATH="$4"
        scp -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/
        exit 1
    fi
    echo "File transfer complete"

else
    echo "Invalid number of arguments passed.. be sure to enter 3 or 4 arguments"
    exit 1
fi
