#!/usr/bin/env bash
# Configures a new Ubuntu machine to install and run nginx with a custom index page

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.html

service nginx restart