#!/usr/bin/env bash
# Configures a new Ubuntu machine to install and run nginx with a custom index page

apt-get update -y
apt-get install nginx -y

mkdir -p /var/www/html
echo "Holberton School" | tee /var/www/html/index.html

nginx -t
service nginx restart